site_name: Tecnologies Multimedia

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home:
      - "Documentació": "index.md"
  - Team:
      - "Team": "team.md"
  - "How to execute the project?":
      - "Execute": "execute.md"
  - Filters:
      - "Filters": "filters.md"
  - Processing images:
      - "Processing images": "encoder.md"
  - Utils:
      - "Utils": "utils.md"
